// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    src: "/images/img1.png",
    alt: "Image 1",
    category: "nature",
    title: "image1",
  },
  {
    id: 2,
    src: "/images/img2.jpg",
    alt: "Image 2",
    category: "animals",
    title: "image2",
  },
  {
    id: 3,
    src: "/images/img3.jpg",
    alt: "Image 3",
    category: "animals",
    title: "image3",
  },
  {
    id: 4,
    src: "/images/img4.jpg",
    alt: "Image 4",
    category: "nature",
    title: "image4",
  },
  {
    id: 5,
    src: "/images/img5.jpg",
    alt: "Image 5",
    category: "animals",
    title: "image5",
  },
  {
    id: 6,
    src: "/images/img6.jpg",
    alt: "Image 6",
    category: "nature",
    title: "image6",
  },
  {
    id: 7,
    src: "/images/img7.jpg",
    alt: "Image 7",
    category: "animals",
    title: "image7",
  },
  {
    id: 8,
    src: "/images/img8.jpg",
    alt: "Image 8",
    category: "nature",
    title: "image8",
  },
  {
    id: 9,
    src: "/images/img9.jpg",
    alt: "Image 9",
    category: "animals",
    title: "image9",
  },
  {
    id: 10,
    src: "/images/img10.jpg",
    alt: "Image 10",
    category: "nature",
    title: "image10",
  },
  {
    id: 11,
    src: "/images/img11.jpg",
    alt: "Image 11",
    category: "animals",
    title: "image11",
  },
  {
    id: 12,
    src: "/images/img12.jpg",
    alt: "Image 12",
    category: "nature",
    title: "image12",
  },
  {
    id: 13,
    src: "/images/img13.jpg",
    alt: "Image 13",
    category: "animals",
    title: "image13",
  },
  {
    id: 14,
    src: "/images/img14.jpg",
    alt: "Image 14",
    category: "animals",
    title: "image14",
  },
  {
    id: 15,
    src: "/images/img15.jpg",
    alt: "Image 15",
    category: "nature",
    title: "image15",
  },
];
